#!/usr/bin/env pwsh

$gitDir = git rev-parse --absolute-git-dir
if ($LASTEXITCODE -ne 0) {
  Write-Error 'Not in a git repository.'
  exit 1
}

$diff = git diff --cached
if ([string]::IsNullOrWhiteSpace($diff)) {
  Write-Error "No staged changes found. Stage your changes first with 'git add'."
  exit 1
}

$prompt = @"
Make sure to only generate only the commit message, nothing else. Remove the Generated by claude code statement.
I want just the result, none additional statements.

Follow the Conventional Commits format strictly for commit messages. Use the structure below:

``````
<type>[optional scope]: <gitmoji> <description>

[optional body]
``````

Guidelines:

1. **Type and Scope**: Choose an appropriate type (e.g., ``feat``, ``fix``) and optional scope to describe the affected module or feature.

2. **Gitmoji**: Include a relevant ``gitmoji`` that best represents the nature of the change.

3. **Description**: Write a concise, informative description in the header; use backticks if referencing code or specific terms.

4. **Body**: For additional details, use a well-structured body section:
   - Use bullet points (``*``) for clarity.
   - Clearly describe the motivation, context, or technical details behind the change, if applicable.
   - Make sure to add a newline between the header and body.
   - Make sure to only use raw text, no backticks or leading and trailing newlines.
Commit messages should be clear, informative, and professional, aiding readability and project tracking.

Here are my staged changes:

$diff

"@

$commitMsg = claude -p $prompt

if ($LASTEXITCODE -ne 0) {
  Write-Error "Claude CLI failed with exit code: $LASTEXITCODE"
  exit 1
}

if ([string]::IsNullOrWhiteSpace($commitMsg)) {
  Write-Error 'Claude returned an empty commit message.'
  exit 1
}

$commitMsg = $commitMsg -replace '`'
$commitMsg = ($commitMsg -join "`n").trim()

$commitMsg | Set-Content "$gitDir/CLAUDE_MSG" -NoNewline

Write-Host $commitMsg
Write-Host ""
Write-Host "Press 'C' in LazyGit to open editor with this message pre-filled"
