#!/usr/bin/env pwsh

function New-ClaudeCommitMessage {
  <#
    .SYNOPSIS
        Generate a commit message using Claude AI based on staged git changes.

    .DESCRIPTION
        This function analyzes your staged git changes and uses Claude CLI to generate
        a conventional commit message with gitmoji. The generated message follows the
        Conventional Commits format with proper type, scope, gitmoji, and description.

    .EXAMPLE
        New-ClaudeCommitMessage
        Generates a commit message for currently staged changes and prompts for confirmation.

    .NOTES
        Requires:
        - Git repository
        - Claude CLI installed and available in PATH
        - Staged changes (use 'git add' first)
        - tmux (optional, for edit mode)
    #>
  param()

  # Check if we're in a git repository
  if (-not (git rev-parse --is-inside-work-tree 2>$null)) {
    throw 'Not in a git repository.'
  }

  # Get staged diff
  $diff = git diff --cached

  if ($LASTEXITCODE -ne 0) {
    throw "Failed to get staged changes. Git error code: $LASTEXITCODE"
  }

  if ([string]::IsNullOrWhiteSpace($diff)) {
    throw "No staged changes found. Stage your changes first with 'git add'."
  }

  # Create commit message using Claude
  $prompt = @"
Make sure to only generate only the commit message, nothing else. Remove the Generated by claude code statement.
Do NOT include any Co-Authored-By lines or attribution footers.
I want just the result, none additional statements.

Follow the Conventional Commits format strictly for commit messages. Use the structure below:

``````
<type>[optional scope]: <gitmoji> <description>

[optional body]
``````

Guidelines:

1. **Type and Scope**: Choose an appropriate type (e.g., ``feat``, ``fix``) and optional scope to describe the affected module or feature.

2. **Gitmoji**: Include a relevant ``gitmoji`` that best represents the nature of the change.

3. **Description**: Write a concise, informative description in the header; use backticks if referencing code or specific terms.

4. **Body**: For additional details, use a well-structured body section:
   - Use bullet points (``*``) for clarity.
   - Clearly describe the motivation, context, or technical details behind the change, if applicable.
   - Make sure to add a newline between the header and body.
   - Make sure to only use raw text, no backticks or leading and trailing newlines.
Commit messages should be clear, informative, and professional, aiding readability and project tracking.

Here are my staged changes:

$diff

"@

  # Check if claude CLI is available
  if (-not (Get-Command claude )) {
    throw 'Claude CLI not found. Please install it first.'
  }

  # Generate commit message
  $commitMsg = claude --model haiku -p $prompt

  if ($LASTEXITCODE -ne 0) {
    throw "Failed to generate commit message. Claude CLI error code: $LASTEXITCODE"
  }

  if ([string]::IsNullOrWhiteSpace($commitMsg)) {
    throw 'Claude returned an empty commit message.'
  }

  $commitMsg = $commitMsg -replace '`'
  $commitMsg = $commitMsg -replace '(?m)^\s*Co-Authored-By:.*$\n?', ''
  $commitMsg = ($commitMsg -join "`n").trim()

  Write-Host 'Generated Commit Message:'
  Write-Host "$commitMsg" -ForegroundColor Green
  $choice = Read-Host 'Use this commit message? (y/n/c to copy to clipboard)'

  switch ($choice.ToLower()) {
    'y' {
      git commit -m $commitMsg
      if ($LASTEXITCODE -ne 0) {
        throw "Git commit failed with error code: $LASTEXITCODE"
      }
    }
    'c' {
      $commitMsg | Set-Clipboard
      Write-Host 'Commit message copied to clipboard.' -ForegroundColor Green
    }
    default {
      Write-Warning 'Commit cancelled.'
    }
  }
}
